ASB 2025.01 - ABI Check updates for libbinder
The 2025.01 ASB backports have brought an update in frameworks/native
for libbinder, which triggers the below build error:

error: VNDK library: libbinder's ABI has INCOMPATIBLE CHANGES
Please check compatibility report at:
/mnt/out/out/lineage-18/soong/.intermediates/frameworks/native/libs/
binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.abidiff

error: Please update ABI references with:
$ANDROID_BUILD_TOP/development/vndk/tools/header-checker/
utils/create_reference_dumps.py -l libbinder
ninja failed with: exit status 1

Running the a.m. script has updated the check dumps accordingly.

Change-Id: I37d59597538c480b1e711dc5b88d3552479b8c23